name: quizwiz
description: QuizWiz is a flashcard app that utilizes the power of AI to make
  flashcards from documents.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bloc_test: ^9.1.3
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  file_picker: ^5.3.2
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  focused_menu: ^1.0.5
  get_it: ^7.6.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  jiffy: ^6.2.1
  lottie: ^2.4.0
  mockito: ^5.4.2
  path_provider: ^2.0.15
  read_pdf_text: ^0.2.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpeg"

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
